import os
import argparse
import json
from script_generator import generate_script
from audio_generator import process_script
from simple_image_gen import generate_thumbnail
from video_editor import create_podcast_video
from youtube_uploader import upload_video

def main():
    parser = argparse.ArgumentParser(description="Auto Podcast Generator & Uploader")
    parser.add_argument("--topic", type=str, required=True, help="Topic text or news content")
    parser.add_argument("--upload", action="store_true", help="Upload to YouTube automatically")
    args = parser.parse_args()

    print("=== Phase 1: Script Generation (LM Studio) ===")
    script = generate_script(args.topic)
    if not script:
        print("Failed to generate script.")
        return
    
    # 脚本保存
    with open("script.json", "w", encoding="utf-8") as f:
        json.dump(script, f, indent=2, ensure_ascii=False)

    print("\n=== Phase 2: Audio Generation (VOICEVOX) ===")
    audio_files = process_script("script.json", "output_audio")
    if not audio_files:
        print("Failed to generate audio.")
        return

    print("\n=== Phase 3: Thumbnail Generation (Stable Diffusion) ===")
    # 脚本のタイトルを元にプロンプトを作成
    title = script.get("title", "Podcast Episode")
    prompt = f"masterpiece, best quality, anime style, a radio studio with a calm anime narrator speaking into a microphone, text title '{title}', on air sign, highly detailed, 4k"
    thumbnail_path = generate_thumbnail(prompt, "thumbnail.png")
    if not thumbnail_path:
        print("Failed to generate thumbnail.")
        return

    print("\n=== Phase 4: Video Editing (MoviePy) ===")
    video_path = create_podcast_video(thumbnail_path, "output_audio", "final_video.mp4")
    if not video_path:
        print("Failed to create video.")
        return

    if args.upload:
        print("\n=== Phase 5: YouTube Upload ===")
        description = "This video was automatically generated by AI.\n\n" + "\n".join([f"{d['speaker']}: {d['text']}" for d in script['dialogue']])
        # 長すぎる場合はカット
        if len(description) > 4500:
            description = description[:4500] + "..."
            
        upload_video(video_path, title, description, privacy_status="public")
    else:
        print("\nSkipping upload. Use --upload to upload to YouTube.")
    
    print("\nAll Done! 🎉")

if __name__ == "__main__":
    main()
